### ISSUE TITLE
Anmerkungen

### ISSUE THREAD

**Issue by freetwix** [Darjusch/eventMap#1]
# Docs
Interessante Beispielprojekte mit GMaps

* https://github.com/fcaravana/mapquest
  * statische daten aus json datei auslesen
* https://github.com/triminhvi/FEND-NeighborHood-Map
  * einfaches javascript, kein Framework/Architecture Pattern

Hosting auf Github als statische Projekt-Seite (unter https://Darjusch.github.io/eventMap/)

* https://help.github.com/articles/user-organization-and-project-pages/

Backend für Sharing von Locations (advanced)

* https://developers.google.com/maps/documentation/javascript/firebase
  * firebase mit anonymen login
  * HINT: um das ganze bei JSFiddle zum laufen zu bekommen, muss man den JSFiddle javascript code nochmal rüberkopieren (nur den <script> part)

# ToDos

Ich würde bis morgen abend folgendes versuchen umzusetzen

* [ ] statische seite auf github zum laufen bekommen (kann man sich bei FEND-NeighborHood-Map anschauen)
* [ ] statische orte mit infoboxen auf der seite abbilden
* [ ] orte neu eintragen können mit daten (ohne weitere persistenz, d.h. auch nicht sichtbar für andere)
